### ISSUE TITLE
Add check for UTF8 String length during creation

### ISSUE THREAD

**Issue by SgtSilvio** [mqtt-bee/mqtt-bee#158]
and remove `MqttBinaryData.isInRange(binary)` check which throws an exception from `encodedLength`

**Comment by christianhoff** [comment]
What should be returned during creation in case of an error? Just null?

**Comment by SgtSilvio** [comment]
Currently we return null for all validation errors in the MqttUTF8StringImpl and MqttUTF8String checks for null and throws an exception. This was done that way to not throw exceptions internally, but only when the user calls the methods from the api package.
We could throw exceptions, but at least without a stacktrace. If so, we should change this for all validation errors.

**Comment by SgtSilvio** [comment]
For checking the encoded size `Utf8.encodedLength` can be used.
Checking the encoded size can be very expensive, so we should perform a simpler check before: Only if `string.length() * 2 > MqttBinaryData.MAX_LENGTH` is true, we need to perform the check.

**Comment by christianhoff** [comment]
Currently the user will get an IllegalArgumentException stating "The string is not a valid UTF-8 encoded String." regardless what went wrong. The user should at least get a meaningful error message, i.e. string to long or string contains invalid characters. So I would vote to have at least these two exceptions on the API level.

**Comment by christianhoff** [comment]
What about having a flag whether `MqttUtf8StringImpl#from` should throw on error or not? When used internally it could return null. When used through the API it throws.

**Comment by SgtSilvio** [comment]
I think it is ok to allways throw exceptions for the MqttUtf8StringImpl.from(String)
but not for the MqttUtf8StringImpl.from(byte[]/ByteBuffer) methods

**Comment by christianhoff** [comment]
OK, I will trow exceptions.

One other point, I do not understand your assumption:

> Only if string.length() * 2 > MqttBinaryData.MAX_LENGTH is true, we need to perform the check.

Since UTF-8 uses 1 to 4 bytes for each code point, e.g. all ASCII (0-127) code points will only need one byte in UTF-8.

**Comment by christianhoff** [comment]
But what if we have characters that need 2 bytes in UTF-16 but 3 bytes in UTF-8?

According to https://en.wikipedia.org/wiki/Comparison_of_Unicode_encodings code points from 000800-003FFF and 004000-00FFFF need 2 bytes in UTF-16 but 3 bytes in UTF-8.

Lets make an example:
* assume MqttBinaryData.MAX_LENGTH = 10
* assume we have a string consisting of 4 chars as described above
* then string.length = 4 and 4 * 2 = 8 which is not bigger than 10, hence no exception
* **but** the number of bytes of the string in UTF-8 would be 12 which is bigger than 10, so we should have thrown an exception

So we could implement this fast check only with using a factor 3 instead of 2.

BTW, if I change the API to always throw, we need to adapt 357 tests that will fail because of the change. Should we anyway go with this approach? The solution described above (flag to enable exceptions) would not change the contract of the method for existing code that uses the method.

**Comment by SgtSilvio** [comment]
You are right, the check has to multiply with 3.
Why would the tests be broken? The exceptions should be RuntimeExceptions and therefore the API does not change and so the tests do not need to be changed.

**Comment by christianhoff** [comment]
Sorry, my fault, wrong boolean expression (one NOT to little).
